export const GET_ALBUM_REQUEST = 'GET_ALBUM_REQUEST';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAILURE = 'GET_ALBUM_FAILURE';

export const CURRENT_POSITION_REQUEST = 'CURRENT_POSITION_REQUEST';
export const CURRENT_POSITION_SUCCESS = 'CURRENT_POSITION_SUCCESS';
export const CURRENT_POSITION_FAILURE = 'CURRENT_POSITION_FAILURE';
